#!/usr/bin/env bash
set -euo pipefail

cd /home/siguangchen/zyj/FUcopy1

env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/run_heterogeneity_comparison.py --dataset-base Cifar10 --dataset-prefix clientscale_c10 --experiment-name client_count_severe_c10 --goal test --algorithm FedAvg --model ResNet18 --device cuda --device-id 0 --python /home/siguangchen/anaconda3/envs/zyj/bin/python --levels severe --methods fu fedau fedcsa fedosd retrain --num-clients 10 --target-client-id 5 --partition dir --alpha-severe 0.1 --balance --summary-only
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/run_heterogeneity_comparison.py --dataset-base Cifar10 --dataset-prefix clientscale_c20 --experiment-name client_count_severe_c20 --goal test --algorithm FedAvg --model ResNet18 --device cuda --device-id 0 --python /home/siguangchen/anaconda3/envs/zyj/bin/python --levels severe --methods fu fedau fedcsa fedosd retrain --num-clients 20 --target-client-id 5 --partition dir --alpha-severe 0.1 --balance --summary-only
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/run_heterogeneity_comparison.py --dataset-base Cifar10 --dataset-prefix clientscale_c50 --experiment-name client_count_severe_c50 --goal test --algorithm FedAvg --model ResNet18 --device cuda --device-id 0 --python /home/siguangchen/anaconda3/envs/zyj/bin/python --levels severe --methods fu fedau fedcsa fedosd retrain --num-clients 50 --target-client-id 5 --partition dir --alpha-severe 0.1 --balance --summary-only
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/run_heterogeneity_comparison.py --dataset-base Cifar10 --dataset-prefix clientscale_c100 --experiment-name client_count_severe_c100 --goal test --algorithm FedAvg --model ResNet18 --device cuda --device-id 0 --python /home/siguangchen/anaconda3/envs/zyj/bin/python --levels severe --methods fu fedau fedcsa fedosd retrain --num-clients 100 --target-client-id 5 --partition dir --alpha-severe 0.1 --balance --summary-only
