#!/usr/bin/env bash
set -euo pipefail

cd /home/siguangchen/zyj/FUcopy1

env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_mild --eval_gap 10 --result_tag fu_mild --forget_strategy gradient_reversal --enable_backdoor_attack false
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_mild --eval_gap 10 --result_tag fedau_mild --forget_strategy fedau --enable_backdoor_attack false
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_mild --eval_gap 10 --result_tag fedcsa_mild --forget_strategy fedcsa --enable_backdoor_attack false --load_saved_model true --saved_model_path /home/siguangchen/zyj/FUcopy1/results/exp_configs/global_model_Cifar10_hetero_clean_s42_mild_FedAvg_test_1_fu_mild.pt
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_mild --eval_gap 10 --result_tag fedosd_mild --forget_strategy fedosd --enable_backdoor_attack false --load_saved_model true --saved_model_path /home/siguangchen/zyj/FUcopy1/results/exp_configs/global_model_Cifar10_hetero_clean_s42_mild_FedAvg_test_1_fu_mild.pt
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_mild --eval_gap 10 --mia_pre_model_source global_model --result_tag retrain_mild --forget_strategy gradient_reversal --enable_backdoor_attack false --retrain_only true
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_moderate --eval_gap 10 --result_tag fu_moderate --forget_strategy gradient_reversal --enable_backdoor_attack false
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_moderate --eval_gap 10 --result_tag fedau_moderate --forget_strategy fedau --enable_backdoor_attack false
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_moderate --eval_gap 10 --result_tag fedcsa_moderate --forget_strategy fedcsa --enable_backdoor_attack false --load_saved_model true --saved_model_path /home/siguangchen/zyj/FUcopy1/results/exp_configs/global_model_Cifar10_hetero_clean_s42_moderate_FedAvg_test_1_fu_moderate.pt
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_moderate --eval_gap 10 --result_tag fedosd_moderate --forget_strategy fedosd --enable_backdoor_attack false --load_saved_model true --saved_model_path /home/siguangchen/zyj/FUcopy1/results/exp_configs/global_model_Cifar10_hetero_clean_s42_moderate_FedAvg_test_1_fu_moderate.pt
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_moderate --eval_gap 10 --mia_pre_model_source global_model --result_tag retrain_moderate --forget_strategy gradient_reversal --enable_backdoor_attack false --retrain_only true
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_severe --eval_gap 10 --result_tag fu_severe --forget_strategy gradient_reversal --enable_backdoor_attack false --load_saved_model true --saved_model_path /home/siguangchen/zyj/FUcopy1/results/exp_configs/global_model_Cifar10_hetero_clean_s42_severe_FedAvg_test_1_fu_severe.pt
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_severe --eval_gap 10 --result_tag fedau_severe --forget_strategy fedau --enable_backdoor_attack false
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_severe --eval_gap 10 --result_tag fedcsa_severe --forget_strategy fedcsa --enable_backdoor_attack false --load_saved_model true --saved_model_path /home/siguangchen/zyj/FUcopy1/results/exp_configs/global_model_Cifar10_hetero_clean_s42_severe_FedAvg_test_1_fu_severe.pt
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_severe --eval_gap 10 --result_tag fedosd_severe --forget_strategy fedosd --enable_backdoor_attack false --load_saved_model true --saved_model_path /home/siguangchen/zyj/FUcopy1/results/exp_configs/global_model_Cifar10_hetero_clean_s42_severe_FedAvg_test_1_fu_severe.pt
env -u LD_LIBRARY_PATH /home/siguangchen/anaconda3/envs/zyj/bin/python -u system/main.py --dataset Cifar10_hetero_clean_s42_severe --eval_gap 10 --mia_pre_model_source global_model --result_tag retrain_severe --forget_strategy gradient_reversal --enable_backdoor_attack false --retrain_only true
